FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y vim less man
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y gcc cmake make libfuse-dev libmbedtls-dev ruby-dev
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y pkg-config

COPY . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
